### ISSUE TITLE
Erro ao compilar expressão de teste (schematron) contendo predicados.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#101]
Informação do ambiente:

```
(packtools)gustavofonseca@PAT113-SCIELO-2:packtools (master) stylechecker --sysinfo
{
  "libxml_compiled_version": "2.9.4",
  "libxml_version": "2.9.4",
  "libxslt_compiled_version": "1.1.29",
  "libxslt_version": "1.1.29",
  "lxml_version": "3.6.4.0",
  "packtools_version": "1.3.1",
  "python_version": "3.5.2",
  "system_path": [
    "/Users/gustavofonseca/prj/envs/packtools/bin",
    "/Users/gustavofonseca/prj/github/packtools",
    "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/picles.plumber-0.11-py3.5.egg",
    "/Users/gustavofonseca/prj/envs/packtools/lib/python35.zip",
    "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5",
    "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/plat-darwin",
    "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/lib-dynload",
    "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5",
    "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin",
    "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages"
  ],
  "xml_catalog_files": "/Users/gustavofonseca/prj/github/packtools/packtools/catalogs/scielo-publishing-schema.xml"
}
```

Relatório da execução dos testes de unidade (apenas o subconjunto relevante):

```
(packtools)gustavofonseca@PAT113-SCIELO-2:packtools (master) python setup.py test -s tests.test_schematron_1_5.PersonGroupTests
running test
running egg_info
writing packtools.egg-info/PKG-INFO
writing top-level names to packtools.egg-info/top_level.txt
writing entry points to packtools.egg-info/entry_points.txt
writing dependency_links to packtools.egg-info/dependency_links.txt
writing requirements to packtools.egg-info/requires.txt
reading manifest file 'packtools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt'
warning: no files found matching '*.md'
warning: no files found matching '*.xsd' under directory 'packtools'
writing manifest file 'packtools.egg-info/SOURCES.txt'
running build_ext
test_allowed_types (tests.test_schematron_1_5.PersonGroupTests) ... ERROR
test_disallowed_type (tests.test_schematron_1_5.PersonGroupTests) ... ERROR
test_loose_text_below_element_citation_node (tests.test_schematron_1_5.PersonGroupTests) ... ERROR
test_loose_text_below_product_node (tests.test_schematron_1_5.PersonGroupTests) ... ERROR
test_missing_type (tests.test_schematron_1_5.PersonGroupTests) ... ERROR
test_missing_type_at_product (tests.test_schematron_1_5.PersonGroupTests) ... ERROR
test_with_type (tests.test_schematron_1_5.PersonGroupTests) ... ERROR

======================================================================
ERROR: test_allowed_types (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3603, in test_allowed_types
    self.assertTrue(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

======================================================================
ERROR: test_disallowed_type (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3622, in test_disallowed_type
    self.assertFalse(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

======================================================================
ERROR: test_loose_text_below_element_citation_node (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3641, in test_loose_text_below_element_citation_node
    self.assertFalse(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

======================================================================
ERROR: test_loose_text_below_product_node (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3669, in test_loose_text_below_product_node
    self.assertFalse(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

======================================================================
ERROR: test_missing_type (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3547, in test_missing_type
    self.assertFalse(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

======================================================================
ERROR: test_missing_type_at_product (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3564, in test_missing_type_at_product
    self.assertFalse(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

======================================================================
ERROR: test_with_type (tests.test_schematron_1_5.PersonGroupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 3583, in test_with_type
    self.assertTrue(self._run_validation(sample))
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 32, in _run_validation
    schematron = TestPhase(self.sch_phase, self.cache)
  File "/Users/gustavofonseca/prj/github/packtools/tests/test_schematron_1_5.py", line 22, in TestPhase
    phase = isoschematron.Schematron(SCH, phase=phase_name)
  File "/Users/gustavofonseca/prj/envs/packtools/lib/python3.5/site-packages/lxml/isoschematron/__init__.py", line 288, in __init__
    self._validator = _etree.XSLT(validator_xslt)
  File "src/lxml/xslt.pxi", line 409, in lxml.etree.XSLT.__init__ (src/lxml/lxml.etree.c:173519)
lxml.etree.XSLTParseError: xsl:when : could not compile test expression 'parent::.[local-name() = 'product'] or                      string-length(normalize-space(text())) = 0'

----------------------------------------------------------------------
Ran 7 tests in 4.218s

FAILED (errors=7)
```

**Comment by gustavofonseca** [comment]
É importante dizer que o erro não foi reproduzido quando a `lxml` foi linkada com `libxml: 2.9.3` e `libxslt: 1.1.28`.
