### ISSUE TITLE
[html] ERRO na geração de HTML xsl:comment : '--' or ending '-' not allowed in comment

### ISSUE THREAD

**Issue by jfunez** [scieloorg/packtools#157]
encontramos um erro na geração de html:
```
lxml.etree.XSLTApplyError: xsl:comment : '--' or ending '-' not allowed in comment
```

- Versão do Packtools: **v2.3.6**
- É valido segundo o stylechecker?: **Sim**
- Testado no branch master: **Sim!**
- PID de artigo de exemplo: `S0104-12902018000200354` 

## Saída do stylechecker:

```
stylechecker 1984-0470-sausoc-27-02-354.xml
Please wait, this may take a while...
[
  {
    "_xml": "1984-0470-sausoc-27-02-354.xml",
    "assets": [],
    "dtd_errors": [],
    "is_valid": true,
    "style_errors": {}
  }
]
```

## passos para reproduzir o erro:

1. Baixar o xml do artigo com PID: S0104-12902018000200354
1. executar o htmlgenerator: `htmlgenerator 1984-0470-sausoc-27-02-354.xml` 

Traceback do erro: 
```
Traceback (most recent call last):
  File "~/Envs/packtools/bin/htmlgenerator", line 11, in <module>
    load_entry_point('packtools', 'console_scripts', 'htmlgenerator')()
  File "~/Envs/packtools/lib/python2.7/site-packages/packtools/utils.py", line 134, in wrapper
    _return = wrapped(*args, **kwargs)
  File "~/Envs/packtools/lib/python2.7/site-packages/packtools/htmlgenerator.py", line 97, in main
    for lang, trans_result in html_generator:
  File "~/Envs/packtools/lib/python2.7/site-packages/packtools/domain.py", line 575, in __iter__
    res_html = self.generate(lang)
  File "~/Envs/packtools/lib/python2.7/site-packages/packtools/domain.py", line 603, in generate
    url_download_ris=etree.XSLT.strparam(self.url_download_ris or ''),
  File "src/lxml/xslt.pxi", line 600, in lxml.etree.XSLT.__call__
lxml.etree.XSLTApplyError: xsl:comment : '--' or ending '-' not allowed in comment
```

**Comment by gustavofonseca** [comment]
[1984-0470-sausoc-27-02-354.xml.txt](https://github.com/scieloorg/packtools/files/2198947/1984-0470-sausoc-27-02-354.xml.txt)
