### ISSUE TITLE
Stylechecker com problema no Windows

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#226]
### Descrição do problema
O programa está instalado corretamente, pois ao executar no Windows o `-h` e `--version` funcionam e também retorna erro com XMLs malformados.

Contudo ao executar em um XML bom ele apenas retorna _Please wait, this may take a while..._ e termina a execução.

Olhando [este issue](https://github.com/scieloorg/packtools/issues/127) tentei setar a variável mencionada (`$env:PACKTOOLS_SUPPORTED_SPS_VERSIONS = "sps-1.8:sps-1.9"
`) mas nada mudou.

### Passos para reproduzir o problema
1. Instale conforme meu ambiente utilizado
2. rode o comando com o arquivo XML no Anexo
3. Observe que a saída é apenas _Please wait, this may take a while..._ e nada mais.

### Comportamento esperado
Esperava que fosse exibido o JSON com o resultado da validação.

### Screenshots ou vídeos
```
stylechecker --version
2.6.1

stylechecker arquivo-ruim.xml #arquivo inválido
Please wait, this may take a while...
Something went wrong while working on G:\pasta\arquivo-ruim.xml: Start tag expected, '<' not found, line 1, column 1 (line 1).
```
### Anexos
Esta seção é opcional. Utilize para referenciar arquivos que servem de insumo para reproduzir o erro, ex:
- XML utilizado: 
[2179-975X-alb-32-e1.zip](https://github.com/scieloorg/packtools/files/4455396/2179-975X-alb-32-e1.zip)

### Ambiente utilizado
 - Windows 10
 - Powershell
 - python 2.7.16 (32bits)
 - [lxml-3.7.3.win32-py2.7.exe](https://files.pythonhosted.org/packages/a3/f6/a28c5cf63873f6c55a3eb7857b736379229b85ba918261d2e88cf886905e/lxml-3.7.3.win32-py2.7.exe)
 - [packtools-2.6.1-py2.py3-none-any.whl](https://files.pythonhosted.org/packages/d1/9a/0c514740dca3b61ecb20097e050fc3b3607fecc933402587a32b7c2a692c/packtools-2.6.1-py2.py3-none-any.whl) instalado conforme [as instruções](https://packtools.readthedocs.io/en/latest/install.html#installing-on-windows)

**Comment by gustavofonseca** [comment]
@lpanebr, cole aqui por gentileza as mensagens no nível _debug_, com o comando: `stylechecker --loglevel debug arquivo-ruim.xml`.

**Comment by lpanebr** [comment]
**Segue com XML bom. Mesmo do anexo:**
```
stylechecker --loglevel debug 2179-975X-alb-32-e1.xml
Please wait, this may take a while...
2020-04-09 15:53:01,915 [INFO] packtools.stylechecker: running with catalog: SciELO Style Catalog for Packtools
2020-04-09 15:53:01,924 [INFO] packtools.stylechecker: starting validation of "G:\Drives compartilhados\Revistas\acta\xml\2179-975X-alb-32_teste\2179-975X-alb-32-e1.xml"
2020-04-09 15:53:01,961 [INFO] packtools.domain: auto-loading style validations for version "sps-1.9"
2020-04-09 15:53:02,619 [INFO] packtools.domain: fetching the DOCTYPE declaration
2020-04-09 15:53:02,619 [INFO] packtools.domain: fetching the PUBLIC-ID in DOCTYPE declaration
2020-04-09 15:53:02,619 [ERROR] packtools.stylechecker: cannot validate (DTD is not set)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\packtools\stylechecker.py", line 246, in _main
    summary = summarize(validator, assets_basedir=assetsdir_files)
  File "c:\python27\lib\site-packages\packtools\stylechecker.py", line 92, in summarize
    dtd_is_valid, dtd_errors = validator.validate()
  File "c:\python27\lib\site-packages\packtools\utils.py", line 61, in wrapper
    cache[key] = wrappee(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\packtools\domain.py", line 315, in validate
    raise exceptions.UndefinedDTDError('cannot validate (DTD is not set)')
UndefinedDTDError: cannot validate (DTD is not set)
2020-04-09 15:53:02,634 [INFO] packtools.stylechecker: error validating "G:\Drives compartilhados\Revistas\acta\xml\2179-975X-alb-32_teste\2179-975X-alb-32-e1.xml". Skipping. run with option `--loglevel INFO` for more info
```

**Agora com XML ruim:**
```
 stylechecker --loglevel debug arquivo-ruim.xml
Please wait, this may take a while...
2020-04-09 15:55:19,700 [INFO] packtools.stylechecker: running with catalog: SciELO Style Catalog for Packtools
2020-04-09 15:55:19,701 [INFO] packtools.stylechecker: starting validation of "G:\Drives compartilhados\Revistas\acta\xml\2179-975X-alb-32_teste\arquivo-ruim.xml"
2020-04-09 15:55:19,717 [ERROR] packtools.stylechecker: Start tag expected, '<' not found, line 1, column 1 (line 1)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\packtools\stylechecker.py", line 210, in _main
    validator = get_xmlvalidator(xml, args.nonetwork, args.extrasch)
  File "c:\python27\lib\site-packages\packtools\stylechecker.py", line 47, in get_xmlvalidator
    parsed_xml = packtools.XML(xmlpath, no_network=no_network)
  File "c:\python27\lib\site-packages\packtools\utils.py", line 100, in XML
    xml = etree.parse(file, parser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src\lxml\lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:117848)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src\lxml\lxml.etree.c:118195)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src\lxml\lxml.etree.c:117107)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src\lxml\lxml.etree.c:111653)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:105671)
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1 (line 1)
Something went wrong while working on G:\Drives compartilhados\Revistas\acta\xml\2179-975X-alb-32_teste\arquivo-ruim.xml: Start tag expected, '<' not found, line 1, column 1 (line 1).
```

**Comment by lpanebr** [comment]
> @lpanebr, cole aqui por gentileza as mensagens no nível _debug_, com o comando: `stylechecker --loglevel debug arquivo-ruim.xml`.

Bom dia @gustavofonseca 

Obrigado pr ter respondido tão rápido e me desculpe ter demorado em devolver a informação.

Quando puder dar uma olhada agradeço!! Vai facilitar a vida da equipe que agora está em home office com acesso mais complexo ao nosso server no escritório. ;-)

**Comment by gustavofonseca** [comment]
@lpanebr, desculpe a demora. Infelizmente eu não tenho uma máquina Windows para recriar seu ambiente e tentar reproduzir o problema, mas vou tentar trazer alguma luz. 

Eu já vi o problema observado com o *XML bom* quando a *libxml2* não conseguia carregar a DTD definida pelos *identifiers* do *doctype* do XML. Basicamente durante o *parsing* do XML o packtools lê a *xml-declaration* e *doctype* para parametrizar o processo de parsing, informando ao parser qual o conjunto de caracteres usado na codificação do arquivo e qual a DTD utilizada. A escolha da DTD se dá a partir do que está definido no *system identifier* do *doctype*: 

```xml
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" "JATS-journalpublishing1.dtd">
```

O *system-identifier* é o fragmento `"JATS-journalpublishing1.dtd"`. Este fragmento representa uma *URI* de onde a *libxml2* carregará a DTD. A SciELO PS pede que seja usada uma *URI relativa* ao XML, onde muito provavelmente a DTD não está de fato, daí o erro observado (`DTD is not set`). A maneira de contornar isso é por meio da configuração dos catálogos da *libxml2*. Basicamente os catálogos nos permitem mapear os identificadores do *doctype* para outras *URI*s, como para uma cópia da DTD que é distribuída junto do packtools, conforme descrito em https://packtools.readthedocs.io/en/latest/quickstart.html#xml-catalog-configuration.

Já o *XML ruim*, aparentemente há um problema sintático no XML. Você poderia me anexar ele no comentário?

**Comment by lpanebr** [comment]
Obrigado @gustavofonseca 

Setar a `XML_CATALOG_FILES ` RESOLVEU!!

```
$env:XML_CATALOG_FILES  = "c:\python27\lib\site-packages\packtools\catalogs\scielo-publishing-schema.xml"
```

Não se preocupe com o xml ruim. Eu apenas incluí um espaço na 1ª linha pra torna-lo inválido!

RESOLVIDO
