### ISSUE TITLE
Exceção *lxml.etree.XSLTApplyError* ao gerar a pré-visualização em HTML de artigo.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#88]
Traceback:

```
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/envs/packtools/bin/htmlgenerator", line 9, in <module>
    load_entry_point('packtools==1.2dev-20160426', 'console_scripts', 'htmlgenerator')()
  File "/Users/gustavofonseca/prj/github/packtools/packtools/utils.py", line 118, in wrapper
    _return = wrapped(*args, **kwargs)
  File "/Users/gustavofonseca/prj/github/packtools/packtools/htmlgenerator.py", line 71, in main
    for lang, trans_result in html_generator:
  File "/Users/gustavofonseca/prj/github/packtools/packtools/domain.py", line 485, in __iter__
    res_html = self.generate(lang)
  File "/Users/gustavofonseca/prj/github/packtools/packtools/domain.py", line 508, in generate
    styles_css_path=etree.XSLT.strparam(self.css or ''),
  File "src/lxml/xslt.pxi", line 599, in lxml.etree.XSLT.__call__ (src/lxml/lxml.etree.c:187652)
lxml.etree.XSLTApplyError: XPath evaluation returned no result.
```

Obs.:  O arquivo XML teve a extensão alterada para .txt para driblar a restrição do github.
[1678-4170-abc-10-01-00021.txt](https://github.com/scieloorg/packtools/files/237256/1678-4170-abc-10-01-00021.txt)

**Comment by gustavofonseca** [comment]
O erro não é mais reproduzido após a reimplementação do gerador de HTMLs.
